### ISSUE TITLE
Same price for every item in the cart.

### ISSUE THREAD

**Issue by rohanjaswal2507** [CSEC-NITH/foodie#1]
When any item is added to the cart, it's price in the cart is shown ₹300.

**Comment by sukhbir-singh** [comment]
The issue is fixed corresponding to [commit](https://github.com/CSEC-NITH/foodie/commit/ca91794d63f99dc9cbf1cbf623ec84880019a889)

**Comment by sukhbir-singh** [comment]
We have also introduced some improvements in App, like..

- changing user profile layout, 

- disabled button instead of add to card button on adding to cart

- And displaying restaurant name with meal present in cart. 

@rohanjaswal2507  sir do check updated app at [link](https://github.com/CSEC-NITH/foodie/raw/master/Foodie_1.3.apk)
